apiVersion: v1
kind: ConfigMap
metadata:
  name: prometheus-config
  namespace: monitoring
data:
  prometheus.yml: |
    global:
      scrape_interval:     15s # Scrape interval set to 15 seconds
      evaluation_interval: 15s # Evaluate rules every 15 seconds

    # Scrape configuration - Scrape Prometheus itself

    scrape_configs:

      - job_name: 'prometheus'

        static_configs:
        - targets: ['localhost:9090']